import 'package:firebase_auth/firebase_auth.dart';
import 'package:get/get.dart';
import 'package:learn2aid/features/domain/entities/feedback_entity.dart';
import 'package:learn2aid/features/domain/usecases/submit_feedback_usecase.dart';

class FeedbackController extends GetxController {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final SubmitFeedbackUseCase submitFeedbackUseCase;

  FeedbackController({required this.submitFeedbackUseCase});

  var isLoading = false.obs;
  var error = ''.obs;
  var rating = 0.0.obs;
  
  Future<void> submitFeedback({
    required String message,
    required double rating,
    String? name,
  }) async {
    try {
      isLoading.value = true;
      error.value = '';
      
      // Check if user is logged in
      final user = _auth.currentUser;
      if (user == null) {
        error.value = 'You need to be logged in to submit feedback';
        return;
      }

      final feedback = FeedbackEntity(
        id: '', // ID will be generated by Firestore
        userId: user.uid,
        message: message,
        createdAt: DateTime.now(),
        rating: rating,
        email: user.email ?? '',
        name: name ?? user.displayName,
      );

      await submitFeedbackUseCase(feedback);
      Get.snackbar('Success', 'Thank you for your feedback!');
    } catch (e) {
      error.value = e.toString();
      Get.snackbar('Error', 'Could not submit feedback: ${e.toString()}');
    } finally {
      isLoading.value = false;
    }
  }

  void updateRating(double value) {
    rating.value = value;
  }
}